version: '3'
services:
  geoserver:
    build:
      context: .
      args:
        - GEOSERVER_VERSION=2.18.2
        - CORS_ENABLED=true
        - CORS_ALLOWED_METHODS=GET,POST,PUT,HEAD,OPTIONS
    ports:
      - 8080:8080
    environment:
      - DOWNLOAD_EXTENSIONS=true
      - STABLE_EXTENSIONS=wps,csw
      - INITIAL_MEMORY=1G
      - MAXIMUM_MEMORY=2G
      - JAIEXT_ENABLED=true
      - GEOSERVER_DATA_DIR=/opt/geoserver_data/
    volumes:
      - ./demo_data/geoserver_data:/opt/geoserver_data/:Z
      - ./demo_data/additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
