name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t geoserver-docker.osgeo.org/geoserver:${{ github.sha }} .
      - name: Run trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'geoserver-docker.osgeo.org/geoserver:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
